CREATE TABLE 'users' (
  'id' INTEGER(11) NOT NULL AUTO_INCREMENT,
  'username' VARCHAR(20) NOT NULL DEFAULT '',
  'password' VARCHAR(20) NOT NULL DEFAULT '',
  'email' VARCHAR(100) NOT NULL DEFAULT '',
  'birthdate' DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  'firstname' VARCHAR(50) NOT NULL DEFAULT '',
  'lastname' VARCHAR(50) NOT NULL DEFAULT '',
  'created' DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY ('id')
)